workflows:
  ghostgram-build:
    name: Ghostgram iOS Build
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      xcode: latest
      groups:
        - apple_signing  # здесь твой сертификат настроишь позже
    scripts:
      - name: Init submodules
        script: git submodule update --init --recursive
      - name: Generate Xcode project
        script: python3 build-system/Make/Make.py generateProject
      - name: Build with Bazel
        script: bazel build //Telegram:Telegram --compilation_mode=opt --apple_platform_type=ios
    artifacts:
      - bazel-bin/**/*
      - build/**/*
