scripts:
  - name: Init submodules
    script: git submodule update --init --recursive || true   # добавь || true, чтобы не падал на ошибки

  - name: Generate Xcode project
    script: python3 build-system/Make/Make.py generateProject --configurationPath=build-system/template_minimal_development_configuration.json

  - name: Build with Bazel
    script: bazel build //Telegram:Telegram --compilation_mode=opt --apple_platform_type=ios
