workflows:
  ghostgram-ios-build:
    name: Ghostgram iOS Build
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      xcode: latest
      groups:
        - apple_signing
      vars:
        CONFIG_PATH: build-system/config.json  # твой шаблон, поменян на правильный
        BAZEL_VERSION: 6.5.0
        BAZEL_DISK_CACHE: /tmp/bazel-disk-cache
    scripts:
      - name: Install Bazel
        script: |
          curl -LO https://github.com/bazelbuild/bazel/releases/download/$BAZEL_VERSION/bazel-$BAZEL_VERSION-darwin-arm64
          chmod +x bazel-$BAZEL_VERSION-darwin-arm64
          mv bazel-$BAZEL_VERSION-darwin-arm64 bazel
          ./bazel version
          mkdir -p $BAZEL_DISK_CACHE

      - name: Init submodules
        script: git submodule update --init --recursive || true

      - name: Generate Xcode project
        script: python3 build-system/Make/Make.py generateProject --configurationPath=$CONFIG_PATH || true

      - name: Build with Bazel
        script: |
          ./bazel clean --expunge || true
          ./bazel build //Telegram:Telegram \
            --compilation_mode=opt \
            --apple_platform_type=ios \
            --disk_cache=$BAZEL_DISK_CACHE \
            --verbose_failures \
            --sandbox_debug

    artifacts:
      - bazel-bin/Telegram/Telegram.ipa
      - bazel-bin/**/*
      - build/**/*
      - "**/*.ipa"
